services:
    ping-prophet-app:
        container_name: ping-prophet-app
        image: 'slnww/base_laravel:latest'
        environment:
            XDEBUG_MODE: 'debug,coverage'
            XDEBUG_CONFIG: 'client_host=host.docker.internal idekey=${APP_NAME} log_level=0'
            PHP_IDE_CONFIG: 'serverName=${APP_NAME}'
            SSL_MODE: 'mixed'
            PHP_FPM_POOL_NAME: 'app'
            AUTORUN_ENABLED: 'false'
        volumes:
            - '.:/var/www/html'
        labels:
            logging: "promtail"
            logging_jobname: "containerlogs"
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:8080'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        networks:
            - sail
        depends_on:
            - ping-prophet-pgsql
            - ping-prophet-redis

    ping-prophet-pgsql:
        container_name: ping-prophet-pgsql
        image: 'postgres:16.3'
        command: 'postgres -c wal_level=logical -c max_connections=1000'
        ports:
            - '${FORWARD_DB_PORT:-5432}:5432'
        environment:
            PGPASSWORD: '${DB_PASSWORD:-secret}'
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
            - 'ping-prophet-pgsql:/var/lib/postgresql/data'
        networks:
            - sail
        healthcheck:
            test: [ "CMD", "pg_isready", "-q", "-d", "${DB_DATABASE}", "-U", "${DB_USERNAME}" ]
            retries: 3
            timeout: 5s

    ping-prophet-redis:
        container_name: ping-prophet-redis
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'ping-prophet-redis:/data'
        networks:
            - sail
        healthcheck:
            test: [ "CMD", "redis-cli", "ping" ]
            retries: 3
            timeout: 5s

# doesn't work
#    ping-prophet-vite:
#        container_name: ping-prophet-vite
#        build:
#            context: ./docker/vite
#            dockerfile: Dockerfile
#        image: ping-prophet/vite
#        volumes:
#            - .:/var/www/html
#        environment:
#            XDEBUG_MODE: 'off'
#            SSL_MODE: 'off'
#        ports:
#            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
#        networks:
#            - sail
#        entrypoint: ["sh", "-c"]
#        command: ["npm install && npm run dev"]
#        depends_on:
#            -   ping-prophet-app

volumes:
    ping-prophet-pgsql:
        driver: local
    ping-prophet-redis:
        driver: local

networks:
    sail:
        driver: bridge
